Update AutoUpdateEn.yml
-

diff --git a/.github/workflows/AutoUpdateEn.yml b/.github/workflows/AutoUpdateEn.yml
--- a/.github/workflows/AutoUpdateEn.yml
+++ b/.github/workflows/AutoUpdateEn.yml
@@ -84,11 +84,15 @@ jobs:
         if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
         run: |
           actual_filename=$(ls "$GITHUB_WORKSPACE/scripts" | grep "Degrees of Lewdity .*\.zip")
+          if [ -z "$actual_filename" ]; then
+            echo "Error: File not found!"
+            exit 1
+          fi
           echo "Actual filename: $actual_filename"
           unzip "$GITHUB_WORKSPACE/scripts/$actual_filename" -d $GITHUB_WORKSPACE/DoL/
           ls -al "$GITHUB_WORKSPACE/DoL"
-          mv "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity ${{ env.CURRENT_VERSION }}.html" $GITHUB_WORKSPACE/DoLEn.html
-          mv $GITHUB_WORKSPACE/DoLEn.html $GITHUB_WORKSPACE/DoL/
+          mv "$GITHUB_WORKSPACE/DoL/Degrees of Lewdity ${{ env.CURRENT_VERSION }}.html" "$GITHUB_WORKSPACE/DoLEn.html"
+          mv "$GITHUB_WORKSPACE/DoLEn.html" "$GITHUB_WORKSPACE/DoL/"
 
       - name: Update version file
         if: env.download_link != '' && env.CURRENT_VERSION != env.CURRENT_VERSION_EN
